# Generated by Django 5.2.17 on 2026-09-13 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree_level', models.CharField(choices=[('high_school', 'SMA/Sederajat'), ('undergraduate', 'Sarjana (S1)'), ('certification', 'Sertifikasi & Kursus')], default='undergraduate', max_length=20)),
                ('major', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
