# Generated by Django 5.2.17 on 2026-09-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.CharField(choices=[('high_school', 'High School Diploma'), ('undergraduate', "Bachelor's Degree"), ('certification', 'Certification & Courses')], default='undergraduate', max_length=20),
        ),
    ]
